export enum DogBreed {
  SRD = "SRD", // Mixed breed (Sem Raça Definida)
  LABRADOR = "LABRADOR",
  GOLDEN_RETRIEVER = "GOLDEN_RETRIEVER",
  GERMAN_SHEPHERD = "GERMAN_SHEPHERD",
  BULLDOG = "BULLDOG",
  BEAGLE = "BEAGLE",
  POODLE = "POODLE",
  ROTTWEILER = "ROTTWEILER",
  YORKSHIRE_TERRIER = "YORKSHIRE_TERRIER",
  BOXER = "BOXER",
  DACHSHUND = "DACHSHUND",
  SIBERIAN_HUSKY = "SIBERIAN_HUSKY",
  DOBERMAN = "DOBERMAN",
  SHIH_TZU = "SHIH_TZU",
  CHIHUAHUA = "CHIHUAHUA",
  POMERANIAN = "POMERANIAN",
  BORDER_COLLIE = "BORDER_COLLIE",
  AUSTRALIAN_SHEPHERD = "AUSTRALIAN_SHEPHERD",
  COCKER_SPANIEL = "COCKER_SPANIEL",
  MALTESE = "MALTESE",
}

export const DOG_BREEDS = Object.values(DogBreed);
